// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHo4AaeseUiA4xsFRKXHYthkHiV04yVDw',
    appId: '1:189360155161:web:8f4073ec77063dd7319888',
    messagingSenderId: '189360155161',
    projectId: 'reinventory-83f47',
    authDomain: 'reinventory-83f47.firebaseapp.com',
    storageBucket: 'reinventory-83f47.firebasestorage.app',
    measurementId: 'G-9YQZ5ZZL1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMxH9lrUiYA3RqJDGo1s7kIcg8vhZ0918',
    appId: '1:189360155161:android:be305820c396c31e319888',
    messagingSenderId: '189360155161',
    projectId: 'reinventory-83f47',
    storageBucket: 'reinventory-83f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Ljxh8OzNw8XPZFN39uCa23-Tm-h9J04',
    appId: '1:189360155161:ios:a128fad6f0ac22a0319888',
    messagingSenderId: '189360155161',
    projectId: 'reinventory-83f47',
    storageBucket: 'reinventory-83f47.firebasestorage.app',
    iosBundleId: 'com.example.reinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Ljxh8OzNw8XPZFN39uCa23-Tm-h9J04',
    appId: '1:189360155161:ios:a128fad6f0ac22a0319888',
    messagingSenderId: '189360155161',
    projectId: 'reinventory-83f47',
    storageBucket: 'reinventory-83f47.firebasestorage.app',
    iosBundleId: 'com.example.reinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHo4AaeseUiA4xsFRKXHYthkHiV04yVDw',
    appId: '1:189360155161:web:c3b5657ea350bb4f319888',
    messagingSenderId: '189360155161',
    projectId: 'reinventory-83f47',
    authDomain: 'reinventory-83f47.firebaseapp.com',
    storageBucket: 'reinventory-83f47.firebasestorage.app',
    measurementId: 'G-Q88NYS12GY',
  );
}
